config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users
  #get '/name', to: 'homepage#hello'
  root to: redirect('/gossips')
  resources :gossips
  get '/contact', to: 'contact#contact'
  get '/team', to: 'team#team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  has_many :tags, through: :gossips
  
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :zip_code, presence: true, length: { is: 5 }, format: { with: /\A\d{5}\z/, message: 'Zip code should be in the format 12345' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable

  validates :title, presence: true, length: { minimum: 5, maximum: 50 }
  validates :content, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  
  validates :title, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :private_messages_sent, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :private_messages_received, class_name: 'PrivateMessage', foreign_key: 'recipient_id'
  has_many :comments
  has_many :likes
 
  has_secure_password
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 13 }
end

app/controllers/potin_controller.rb
class PotinController < ApplicationController
    def potin
      @gossips = Gossip.all
      @id = params[:id]
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(
        email: params[:user][:email],
        password: params[:user][:password],
        password_confirmation: params[:user][:password_confirmation],
        first_name: params[:user][:first_name],
        last_name: params[:user][:last_name],
        age: params[:user][:age],
        #date_of_birth: params[:user][:date_of_birth],
        city_id: params[:user][:city_id]
      )
  
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render :new
      end
    end
  
    def show
      @user = User.find(params[:id])
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/create_gossip_helper.rb
module CreateGossipHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/potin_helper.rb
module PotinHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      User.find_by(id: session[:user_id])
    end
  
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def user_signed_in?
      !current_user.nil?
    end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
  <nav class="navbar navbar-expand-md fixed-top">
    <div class=" nonnon container-fluid">
        <%= link_to "Gossip Project", root_path, class:"nav-link" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="center1 navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav">
                  <li class="nav-item">
                    <%= link_to "Creer ton gossip !", new_gossip_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Team", team_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Contact", contact_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "Se connecter", new_session_path, class:"nav-link" %>
                  </li>
              </ul>
        </div>
    </div>
  </nav>
 
  </header>

  <body>
    <%= yield %>
  </body>
</html>